export const LOADING_START = "APP/LOADING_START"
export const LOADING_FINISH = "APP/LOADING_FINISH"


export const GET_FOOD = "FOOD/GET_FOOD"

export const GET_CART = "CART/GET_CART"
export const ADD_CART_ITEM = "CART/ADD_CART_ITEM"
export const CHANGE_CART_ITEM = "CART/CHANGE_CART_ITEM"
export const DELETE_CART_ITEM = "CART/DELETE_CART_ITEM"


export const GET_REVIEWS = "REVIEWS/GET_REVIEWS"